### PR TITLE
Replace cucyber pngs with our svg

### PR DESCRIPTION
**Pull request by cyntheticfox**
Since I was messing around with .svg files the other day, I figured I might see how it works on the CU Cyber website.

Afaik, render time doesn't seem to be different from standard pngs, and the resulting image is a little crisper for the background the top-left logo.

### CODE REVIEW

**Comment by cyntheticfox** [comment]
If the Open Graph pr #45 is implemented, the main png will have to be reincluded, as the Open Graph Protocol does not support SVGs

https://indieweb.org/The-Open-Graph-protocol#Does_not_support_SVG_images

**Comment by lilyinstarlight** [comment]
I think it's probably best to keep shield-small.png for what it was used for and potentially use the SVG for the larger graphics if we feel the need to.

The PNGs probably need to be re-rendered anyway because both definitely look fuzzier than they need to.

Also, you changed what the about page looks like (see https://img-svg.dev.cucyber.net/about.html vs https://dev.cucyber.net/about.html). There should really be 3 images instead of 2 because "shield.png" is used for the hero area but it should be swapped with ones that excludes the "CU Cyber" on the bottom.

**Review by lilyinstarlight — CHANGES_REQUESTED** [review]
I guess given this changed the about page negatively (I feel) I probably should have made the previous comment as a review.

**Comment by cyntheticfox** [comment]
I...what?

I literally just rebased and force-pushed ant that closed it?

**Review by lilyinstarlight — APPROVED** [review]

**Pull request merged**
