### PR TITLE
Add Events Page

### PR DESCRIPTION
**Pull request by lilyinstarlight**
Do not merge this PR yet. I'm just putting this here so we can track the PR.

We need to make an initial list of events so we don't just merge a blank page to the website.

### CODE REVIEW

**Comment by lilyinstarlight** [comment]
I think this is ready to be merged. Any comments/suggestions?

**Comment by nbulischeck** [comment]
Looks good to me.

**Review by nbulischeck — APPROVED** [review]
Looks good.

**Review by westonbelk — APPROVED** [review]
Looks good to me.

**Comment by klsimps** [comment]
I like it. I think it is good enough.

**Pull request merged**
